### ISSUE TITLE
"ValueError: not enough values to unpack (expected 2, got 1)"

### ISSUE THREAD

**Issue by nikpap123** [mikeizbicki/cmc-csci181#43]
Because Bert only returns the output class, when I call model(input_tensor), I get "ValueError: not enough values to unpack (expected 2, got 1)". Below is my Bert Implementation and my model(input_tensor) call:
<img width="582" alt="Screenshot 2020-05-10 at 3 39 59 PM" src="https://user-images.githubusercontent.com/32428793/81512328-ba078b00-92d4-11ea-8487-e4bf48309285.png">
<img width="487" alt="Screenshot 2020-05-10 at 3 40 42 PM" src="https://user-images.githubusercontent.com/32428793/81512329-bd027b80-92d4-11ea-913f-06695254218a.png">

It would be great to hear some feedback about how to resolve this issue.

**Comment by n8stringham** [comment]
Hey Nik, I think this might have to do with the fact that we originally implemented our training loop so that we output and updated two values `output_class` and `output_nextchars`. You could modify that code to only expect a single output, or  I think I fixed this by modifying my `BertFineTunning` class to output a dummy variable along with `out`. Then in the training loop I only used `out` to calculate and update loss.

**Comment by nikpap123** [comment]
Thanks Nate, that solved the problem!
